
#  ZONES FOR aperture.lab
zone "aperture.lab" {
    type master;
    file "masters/db.aperture.lab";
    allow-transfer { 192.168.126.0/24; };
};
zone "ocp4.aperture.lab" {
    type master;
    file "masters/db.ocp4.aperture.lab";
    allow-transfer { 192.168.126.0/24; };
};
zone "apps.ocp4.aperture.lab" {
    type master;
    file "masters/db.apps.ocp4.aperture.lab";
    allow-transfer { 192.168.126.0/24; };
};
zone "126.168.192.in-addr.arpa" {
  type master;
  file "db.126.168.192.in-addr.arpa";
  allow-transfer { 192.168.126.0/24; };
}
